language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.4 on Xenial Linux"
      python: "3.4"         # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.5 on Xenial Linux"
      python: "3.5"
    - name: "Python 3.6 on Xenial Linux"
      python: "3.6"         # current default Python on Travis CI
    - name: "Python 3.7 on Xenial Linux"
      python: "3.7"
    - name: "Python 3.8 on Xenial Linux"
      python: "3.8"
    - name: "Python 3.8-dev on Xenial Linux"
      python: "3.8-dev"     # 3.8 development branch
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install: 
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - pip3 install pytest
  - pip3 install pytest-cov
  - pip3 install coveralls
before_script:
  - date
# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script:
  - pytest --cov=timework/
after_success:
  - coveralls
notifications:  
  email:  
    recipients:  
    - github.build.timework@isaacx.com  
    on_success: always  
    on_failure: always
