language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
install: 
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
before_script:
  - date
script:
  - pytest --cov=timework/
after_success:
  - coveralls
notifications:  
  email:  
    recipients:  
    - github.build.timework@isaacx.com  
    on_success: always  
    on_failure: always